#!/bin/bash
dir="/usr/local/bin/scripts/parts"
path="/var/www"
site_available="/etc/apache2/sites-available"
public="public"
name=$1;

echo "Drupal 8 it is!";
echo "";

if [ -d "$path/$name/$public" ] ; then 
        echo "$path/$name/$public exist already!"
else
    echo "Creating $name"
    cd $path
    sudo mkdir $path/$name
    sudo chown developer:www-data $path/$name
    sudo chmod 777 $path/$name
    cd $path/$name 
    composer create-project drupal/drupal:8.4.2 public --stability dev --no-interaction
    sudo chown developer:www-data $path/$name/$public
    cd $path/$name/$public 
    sudo chmod 777 $path/$name/$public/sites/default/
    sudo cp $path/$name/$public/sites/default/default.settings.php $path/$1/$public/sites/default/settings.php
    sudo chmod 777 $path/$name/$public/sites/default/settings.php
    sudo mkdir $path/$name/$public/sites/default/files/
    sudo mkdir $path/$name/$public/sites/default/files/translations 
    sudo chmod 777 -R $path/$name/$public/sites/default/files
    composer require drupal/paragraphs
    composer require drupal/pathauto
    sudo chown developer:www-data $path/$1/$public/sites/default/files
    source $dir/vhost $path $name
    source $dir/createDB $name
    drush si standard --db-url=mysql://root:root@127.0.0.1/$name
    source $dir/apache-restart
    cd $path/$name/$public
    drush en paragraphs
    drush en pathauto
    sudo chmod 775 $path/$name
    echo "Installation complete"
    echo "$path/$name/$public is now created!" 
    echo "Dont forget to add *IP* http://local."$name".serverbox.foobar in your host file! (Your host computer not serverbox)"
fi

exit 1; 
