#!/bin/bash

laravel_version="5.5"
path="/var/www"
site_available="/etc/apache2/sites-available"
public="public"
name=$1;
HTML5_boilerplate_version="6.0.1"

if [ -d "$path/$name/$public" ] ; then 
    echo "$path/$name/$public exist already!"
else
    echo "HTML 5 it is"
    echo ""
    cd $path
    sudo mkdir $path/$name
    sudo chown root:www-data $path/$name
    sudo mkdir $path/$name/$public
    sudo chmod 777 $path/$name/$public
    sudo chown root:www-data $path/$name/$public
    cd $path/$name/$public 
    wget https://github.com/h5bp/html5-boilerplate/releases/download/$HTML5_boilerplate_version/html5-boilerplate_v$HTML5_boilerplate_version.zip
    unzip html5-boilerplate_v$HTML5_boilerplate_version.zip
    sudo rm html5-boilerplate_v$HTML5_boilerplate_version.zip
    source $dir/vhost $path $name
    source $dir/createDB $name
    source $dir/apache-restart
    echo "Installation complete"
    sudo chmod 775 -R $path/$name
    echo "$path/$name/$public is now created!"
    echo "Don't forget to add *IP* http://local."$name".serverbox.foobar in your host file! (Your host computer not serverbox)"
fi

exit 1
