#!/bin/bash
dir="/usr/local/bin/scripts/parts"
version="5.5"
path="/var/www"
site_available="/etc/apache2/sites-available"
public="public"
name=$1;

if [ -d "$path/$name/$public" ] ; then 
    echo "$path/$name/$public exist already!"
else
    echo "Laravel $version it is"
    echo ""
    cd $path
    sudo mkdir $path/$name
    sudo chown root:www-data $path/$name
    cd $path/$name/
    composer create-project --prefer-dist laravel/laravel .
    sudo chmod 777 $path/$name/storage
    source $dir/vhost $path $name
    source $dir/createDB $name
    source $dir/apache-restart
    echo "Installation complete"
    echo "$path/$name/$public is now created!"
    echo "Don't forget to add *IP* http://local."$name".serverbox.foobar in your host file! (Your host computer not serverbox)"
fi
