#!/bin/bash
dir="/usr/local/bin/scripts/parts"
path="/var/www"
site_available="/etc/apache2/sites-available"
public="public"
name=$1;
addsFolder="/var/www/"$name"/public/wp-content/themes/name-theme/adds"
pluginFolder="/var/www/"$name"/public/wp-content/plugins"

echo "WordPress it is!";
echo "";

if [ -d "$path/$name/$public" ] ; then 
    echo "$path/$name/$public exist already!"
else
    echo "Creating $name"
    cd $path
    sudo mkdir $path/$name
    sudo chown developer:www-data $path/$name
    sudo mkdir $path/$name/$public
    sudo chmod 777 $path/$1/$public
    sudo chown developer:www-data $path/$1/$public
    cd $path/$name/$public 
    source $dir/vhost $path $name
    source $dir/createDB $name
    wp core download
    wp config create --dbname=$name --dbuser=root  --dbpass=root --dbhost=localhost
    wp core install --skip-themes --skip-plugins --url=local.$name.serverbox.dev --title=$name --admin_user=root --admin_password=root --admin_email=info@example.com
    source $dir/apache-restart
    echo "Installation complete"
    sudo chmod 775 -R $path/$name
    sudo chown developer:www-data -R $path/$name/$public/
    echo "$path/$name is now created!"
    cd $path/$name/$public/wp-content/themes
    sudo rm -rf *
    sudo mkdir name-theme
    sudo chown developer:www-data name-theme
    cd name-theme
    sudo git clone https://github.com/tdserviceco/wordpress-blank-theme.git .
    sudo rm -rf .git
    sudo chmod 775 -R *
    sudo chown developer:www-data -R *
    cd $addsFolder
    sudo unzip acf.zip
    sudo mv $addsFolder"/advanced-custom-fields-pro" $pluginFolder
    cd ..
    sudo rm -rf adds
    wp theme activate name-theme
    wp plugin activate advanced-custom-fields-pro
    wp cache flush
    echo "Latest wordpress with blank theme installed and ACF pro"
    echo "Dont forget to add *IP* http://local."$name".serverbox.foobar in your host file! (Your host computer not serverbox)"
fi

exit 1;
