#!/bin/bash

##
# Heart and soul!
#

lib="/home/developer/.scripts/version2/lib"
www_folder="/var/www"
name=$1

if [ -z "$name" ]; then
  echo "You forgot to add a name to your project!"
  exit 1
fi

echo ""
echo "###############################"
echo "#                             #"
echo "# Project Setup Version 2.0.0 #"
echo "#                             #"
echo "###############################"
echo ""

# QUIT
quit() {
  echo ""
  echo "Bye bye!"
  cd $www_folder
  sudo rm -R $name
  exit 1
}

cd $www_folder
mkdir $name
sudo chown developer:www-data $name
cd $name
mkdir public
mkdir private
sudo chown developer:www-data public private
echo ""
echo "1. Create a project"
echo "2. Get a project"
echo "3. Delete a project"
echo "Q. Quit"
echo ""
while true; do
  read -p "Please choose a project [1 - 3] " choice
  case $choice in
      [1]* ) source $lib/project-create $name;;
      [2]* ) source $lib/project-get $name;;
      [3]* ) source $lib/project-delete $name;;
      [q/Q]) quit;;
      * ) echo "Please choose 1 - 3!";;
  esac
done