#!/bin/bash

##
# Heart and soul!
#

lib="/home/developer/.scripts/version2/lib"
www_folder="/var/www"
name=$1

if [ -z "$name" ]; then
  echo "You forgot to add a name to your project!"
  exit 1
fi

echo ""
echo "###############################"
echo "#                             #"
echo "# Project Setup Version 2.0.0 #"
echo "#                             #"
echo "###############################"
echo ""

# QUIT
quit() {
  echo ""
  echo "Bye bye!"
  cd $www_folder
  sudo rm -R $name
  exit 1
}

cd $www_folder

if [ -d "$www_folder/$name" ] ; then 
    echo "$name exist already!"
    exit 1
else
mkdir $name

sudo chown developer:www-data $name
cd $name
mkdir public
mkdir private
sudo chown developer:www-data public private
source $lib/project-create $name
fi