#!/bin/bash 
if [ $1 = "wordpress" ]; then
    echo "Purgin "$2
    sudo -i rm -rf /var/www/$2
    sudo -i rm /etc/apache2/sites-available/$2".conf"
    sudo -i a2dissite $2".conf"
    sudo -i systemctl reload apache2
    mysqladmin -uroot -proot drop $2 -f
    echo "Purging done"
    exit 
fi

if [ $1 = "drupal" ]; then
    echo "Purgin "$2
    sudo -i rm -rf /var/www/$2
    sudo -i rm /etc/apache2/sites-available/$2".conf"
    sudo -i a2dissite $2".conf"
    sudo systemctl reload apache2
    mysqladmin -uroot -proot drop $2 -f
    echo "Purging done"
    exit 
fi

if [ $1 = "laravel" ]; then
    echo "Purgin "$2
    sudo -i rm -rf /var/www/$2
    sudo -i rm /etc/apache2/sites-available/$2".conf"
    sudo -i a2dissite $2".conf"
    sudo -i systemctl reload apache2
    mysqladmin -uroot -proot drop $2 -f
    echo "Purging done"
    exit 
fi

if [ $1 = "html5" ]; then
    echo "Purgin "$2
    sudo -i rm -rf /var/www/$2
    sudo -i rm /etc/apache2/sites-available/$2".conf"
    sudo -i a2dissite $2".conf"
    sudo -i systemctl reload apache2
    mysqladmin -uroot -proot drop $2 -f
    echo "Purging done"
    exit 
fi

rm -rf ~/.local/share/Trash/*
