#!/bin/bash

# Laravel 5.X

name=$1
lib="/home/developer/.scripts/version2/lib"
path="/var/www/$name/public"
echo "Laravel 5.x it is"
echo ""
cd $path
composer create-project --prefer-dist laravel/laravel .
sudo chmod 777 $path/$name/storage
source $lib/vhost $path $name
source $lib/createDB $name
source $lib/apache-restart
echo "Installation complete"
echo "http://$name.serverbox.local is now created!"
echo "Don't forget to add *IP* "$name".serverbox.local in your host file! (Your host computer not serverbox)"
exit 1