#!/bin/bash

# Create your web project!

name=$1
www_folder="/var/www"
type="/home/developer/.scripts/version2/web-projects"

# QUIT
quit() {
  echo ""
  echo "Bye bye!"
  cd $www_folder
  sudo rm -R $name
  exit 1
}

echo ""
echo "1. Wordpress 4.9.x"
echo "2. Drupal 8.x.x"
echo "3. Laravel 5.x"
echo "4. Empty project"
echo "Q. Exit"
echo ""
while true; do
  read -p "Please choose a project [1 - 4] or exit " choice
  case $choice in
      [1]* ) source $type/wordpress $name;;
      [2]* ) source $type/drupal $name;;
      [3]* ) source $type/laravel $name;;      
      [4]* ) source $type/empty-project $name;;
      [q/Q]* ) quit;;
      * ) echo "Please choose 1 - 4 or exit!";;
  esac
done

exit 1